In [16]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from datetime import date

import torch
import torch.nn as nn
from stable_baselines3 import A2C
import gpytorch

import yfinance as yf
# import yahoo_finance_api2 as yf
# from yahoo_finance_api2 import share

from custom_env import *
from model import *
from data_util import *

In [17]:
today = date.today()
today

datetime.date(2021, 4, 8)

In [39]:
# Using yahoo_finance_api2
# spy = share.Share('SPY')
# spy.get_historical(share.PERIOD_TYPE_DAY, 1, share.FREQUENCY_TYPE_DAY, 1)

# Using yfinance
spy = yf.Ticker('SPY')
test = spy.history('1mo')
test_split_adjustment = [1 if ss == 0 else ss for ss in test['Stock Splits']]
test['Adj Close'] = test['Close'] * (1 - test['Dividends'] / test['Close']) / np.array(test_split_adjustment)
test['Returns'] = test['Adj Close'].diff()

In [40]:
test.head()

,Open,High,Low,Close,Volume,Dividends,Stock Splits,Adj Close,Returns
Date,,,,,,,,,
2021-03-09,384.590369,388.637112,384.052123,385.906067,113457800,0.0,0,385.906067,NaN
2021-03-10,388.417854,390.122263,386.902827,388.308197,109660800,0.0,0,388.308197,2.402130
2021-03-11,390.949556,394.358375,390.461135,392.245300,86027400,0.0,0,392.245300,3.937103
2021-03-12,390.790066,392.923064,389.922911,392.773560,64608100,0.0,0,392.773560,0.528259
2021-03-15,393.042679,395.394990,390.750200,395.115906,73427200,0.0,0,395.115906,2.342346

In [46]:
features = engineer_features(test).iloc[-1]

In [47]:
features

Open            2.920741e+00
High            3.179346e+00
Low             2.796511e+00
Close           4.065900e+02
Volume          5.567870e+07
Dividends       0.000000e+00
Stock Splits    0.000000e+00
Adj Close       3.085539e+00
Returns         1.929993e+02
Exp MA 5        1.437158e+00
Exp MA 20       3.844882e-01
Exp MA 50       1.663213e-01
Open -1         2.875107e+00
High -1         3.250336e+00
Low -1          2.783829e+00
Adj Close -1    2.966376e+00
Open -2         2.291967e+00
High -2         3.174278e+00
Low -2          2.271688e+00
Adj Close -2    3.027223e+00
Open -3         1.009072e+00
High -3         1.584605e+00
Low -3          9.532932e-01
Adj Close -3    1.569386e+00
Open -4         2.332496e-01
High -4         9.076584e-01
Low -4          2.256438e-01
Adj Close -4    4.842485e-01
Open -5         3.944200e+02
High -5         2.611426e-01
Low -5         -3.549578e-01
Adj Close -5    7.859580e-02
Name: 2021-04-07 00:00:00, dtype: float64

In [29]:
tsla = yf.Ticker('TSLA')
tsla_hist = tsla.history(period='1y')
tsla_hist[tsla_hist['Stock Splits'] != 0]

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2020-08-31,444.609985,500.140015,440.109985,498.320007,118374400,0,5.0

In [ ]:
msft = yf.Ticker("MSFT")

# get stock info
msft.info

# get historical market data
hist = msft.history(period="max")

# show actions (dividends, splits)
msft.actions

# show dividends
msft.dividends

# show splits
msft.splits

# show financials
msft.financials
msft.quarterly_financials

# show major holders
msft.major_holders

# show institutional holders
msft.institutional_holders

# show balance sheet
msft.balance_sheet
msft.quarterly_balance_sheet

# show cashflow
msft.cashflow
msft.quarterly_cashflow

# show earnings
msft.earnings
msft.quarterly_earnings

# show sustainability
msft.sustainability

# show analysts recommendations
msft.recommendations

# show next event (earnings, etc)
msft.calendar